[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_sort_within_sections = true
line_length = 100
known_internal = ["reporter"]

sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "INTERNAL",
    "FIRSTPARTY",
    "LOCALFOLDER",
]

import_heading_stdlib = "Standard Library"
import_heading_firstparty = "validation_report"
import_heading_third_party = "ThirdParty"
import_heading_local_folder = "LocalPkg"


[tool.black]
line-length = 100


[tool.mypy]
ignore_missing_imports = true